# Generated by Django 2.1.5 on 2019-02-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_auto_20190212_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('played', models.CharField(blank=True, max_length=255)),
                ('won', models.CharField(blank=True, max_length=255)),
                ('draws', models.CharField(blank=True, max_length=255)),
                ('lost', models.CharField(blank=True, max_length=255)),
                ('goal_forward', models.CharField(blank=True, max_length=255)),
                ('goal_against', models.CharField(blank=True, max_length=255)),
                ('goal_difference', models.CharField(blank=True, max_length=255)),
                ('points', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='fixtures.Team')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
