# Generated by Django 2.1.5 on 2019-02-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_auto_20190212_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent1_score', models.CharField(blank=True, max_length=255, null=True)),
                ('opponent2_score', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('opponent1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_1', to='fixtures.Team')),
                ('opponent2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_2', to='fixtures.Team')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fixture',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_1', to='fixtures.Tournament'),
        ),
        migrations.AddField(
            model_name='result',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_2', to='fixtures.Tournament'),
        ),
    ]
