# Generated by Django 2.1.5 on 2019-02-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_auto_20190216_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='tournament_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='tournament_date',
            field=models.DateField(null=True),
        ),
    ]
