# Generated by Django 2.1.5 on 2019-02-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0009_remove_fixture_tournament_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='tournament_time',
            field=models.TimeField(null=True),
        ),
    ]
