# Generated by Django 2.1.5 on 2019-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
                'ordering': ['date_created'],
            },
        ),
    ]
