# Generated by Django 2.1.5 on 2019-02-19 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uploadgamepromo_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanOfTheMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_fan', models.CharField(blank=True, max_length=255)),
                ('fan_image', models.ImageField(blank=True, null=True, upload_to='fan/photo/')),
                ('date_created', models.DateTimeField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='ManOfTheMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_man_of_the_match', models.CharField(blank=True, max_length=255)),
                ('man_of_the_match_image', models.ImageField(blank=True, null=True, upload_to='fan/photo/')),
                ('date_created', models.DateTimeField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='TravelWithTheTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_caption', models.CharField(blank=True, max_length=255)),
                ('moment_of_the_match_image', models.ImageField(blank=True, null=True, upload_to='fan/photo/')),
                ('date_created', models.DateTimeField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
