# Generated by Django 2.1.5 on 2019-02-19 22:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fanofthematch_manofthematch_travelwiththeteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('teams_played', models.CharField(blank=True, max_length=255)),
                ('tournament_date', models.DateField(null=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 0, 41, 56, 352826))),
                ('points', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
