# Generated by Django 2.1.5 on 2019-02-19 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 1, 29, 7, 646755)),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='tournament_date',
            field=models.CharField(blank=True, default='Feb. 20, 2019', max_length=255),
        ),
    ]
