# Generated by Django 2.1.5 on 2019-02-20 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190220_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 9, 19, 59, 786544)),
        ),
    ]
