# Generated by Django 2.1.5 on 2019-02-20 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190220_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanofthematch',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 14, 26, 6, 63553)),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 14, 26, 6, 63553)),
        ),
        migrations.AlterField(
            model_name='manofthematch',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 14, 26, 6, 63553)),
        ),
        migrations.AlterField(
            model_name='momementofthematch',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 14, 26, 6, 63553)),
        ),
        migrations.AlterField(
            model_name='travelwiththeteam',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 14, 26, 6, 63553)),
        ),
    ]
