# Generated by Django 2.1.5 on 2019-02-25 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190225_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanofthematch',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manofthematch',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='momementofthematch',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelwiththeteam',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fanofthematch',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 4, 53, 28, 785896)),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 4, 53, 28, 787895)),
        ),
        migrations.AlterField(
            model_name='manofthematch',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 4, 53, 28, 786896)),
        ),
        migrations.AlterField(
            model_name='momementofthematch',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 4, 53, 28, 788894)),
        ),
        migrations.AlterField(
            model_name='travelwiththeteam',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 4, 53, 28, 787895)),
        ),
    ]
