# Generated by Django 2.1.5 on 2019-02-25 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190225_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanofthematch',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 15, 43, 52, 928987)),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 15, 43, 52, 928987)),
        ),
        migrations.AlterField(
            model_name='manofthematch',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 15, 43, 52, 928987)),
        ),
        migrations.AlterField(
            model_name='momementofthematch',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 15, 43, 52, 928987)),
        ),
        migrations.AlterField(
            model_name='travelwiththeteam',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 15, 43, 52, 928987)),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_expiration_date',
            field=models.DateTimeField(default='2000-02-12 19:09:56.668926'),
        ),
    ]
