# Generated by Django 2.1.5 on 2019-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20190215_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentteam',
            name='position',
            field=models.CharField(choices=[('select', 'Select'), ('Goalkeeper', 'Goalkeeper'), ('Forward', 'Forward'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender')], default='All', max_length=20),
        ),
    ]
