# Generated by Django 2.1.5 on 2019-02-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fan/photos')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='fan/videos')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['date_created'],
            },
        ),
    ]
