# Generated by Django 2.1.5 on 2019-02-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['date_created']},
        ),
    ]
